/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream */

#ifndef _Included_de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream
#define _Included_de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream
 * Method:    openFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream
 * Method:    closeFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream_closeFile
  (JNIEnv *, jobject);

/*
 * Class:     de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream
 * Method:    readInt
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_informatik_OfflineToureNPlaner_xz_XZInputStream_readInt
  (JNIEnv *, jobject, jlong, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
